on: [push, workflow_dispatch]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Chef InSpec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

      - name: Accept Chef InSpec License
        run: |
          echo "license:" >> inspec.yml
          echo "  acceptance: 'accept-no-persist'" >> inspec.yml

      - name: run inspec test
        run: |
          --chef-license accept-no-persist
          inspec plugin install inspec-azure 
          export AZURE_SUBSCRIPTION_ID="$(AZURE_SUBSCRIPTION_ID)"
          export AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)"
          export AZURE_CLIENT_SECRET="$(AZURE_CLIENT_SECRET)"
          export AZURE_TENANT_ID="$(AZURE_TENANT_ID)"
          inspec exec . -t azure://
        shell: bash
