name: Chef InSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chef InSpec
        env:
          CHEF_LICENSE: accept-no-persist
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

      - name: Run Chef InSpec Tests
        env:
          CHEF_LICENSE: accept-no-persist
        run: |
          inspec exec . -t azure://
