name: Chef InSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install chef
        uses: actionshub/chef-install@main

      - name: Run Chef InSpec Tests
        run: |
          inspec exec . -t azure://
