on: [push, workflow_dispatch]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@new

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Chef InSpec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

      - name: Run Chef InSpec Tests
        env:
          CHEF_LICENSE: accept-no-persist
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
        run: |
          inspec azure \
            --subscription-id "$AZURE_SUBSCRIPTION_ID" \
            --client-id "$AZURE_CLIENT_ID" \
            --client-secret "$AZURE_CLIENT_SECRET" \
            --tenant-id "$AZURE_TENANT_ID" \
            --controls storage.rb
            inspec exec . -t azure://
