on: [push, workflow_dispatch]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: "storagePrefix=mystore storageSKU=Standard_LRS"
          failOnStdErr: false

      - name: install inspec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
        shell: bash

      - name: run inspec test
        run: |
          inspec plugin install inspec-azure
          export AZURE_SUBSCRIPTION_ID="$(AZURE_SUBSCRIPTION_ID)"
          export AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)"
          export AZURE_CLIENT_SECRET="$(AZURE_CLIENT_SECRET)"
          export AZURE_TENANT_ID="$(AZURE_TENANT_ID)"
          inspec exec . -t azure:// --chef-license=accept-no-persist --reporter cli junit:inspectestresults.xml
