name: Chef InSpec

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Chef InSpec
        run: |
          curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec

      - name: Accept Chef InSpec License
        run: |
          echo "license:" >> inspec.yml
          echo "  acceptance: 'accept-no-persist'" >> inspec.yml

      - name: Run Chef InSpec Tests
        run: |
          inspec exec . -t azure://
